# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ae54c9447b98e6393b76bfba62f2043acb0f0e9a74943e7bae714b326664e522e055fa9960ba06f75b1c769e1f298455ada3bed74058ba04545e764b58751e

test:
  secret_key_base: 2fe5a6988fd759912eb18e8e39d58d82672e878f954757e77ff96fa2af16380ac4f0d4f702116ee61affa3858a3416a288e71f3156175aab4c01967638080ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
